In [14]:
from pathlib import Path
import math
import requests
from io import StringIO

import numpy as np
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from IPython.display import Image, display
import os
import pathlib
import dataretrieval.waterdata as waterdata

DATA_DIR   = pathlib.Path().cwd().parent / 'data'   # adjust if running from a different directory
SWORD_GPKG = pathlib.Path().cwd().parent / 'data'   # na_sword_nodes_v17b_pnw.gpkg lives alongside the notebook

In [3]:
DATA_DIR

WindowsPath('/Users/masa6503/repos/swot-precip-validation/data')

In [29]:
match_distance_maximum=200
stations = pd.read_parquet(DATA_DIR /"dfms_v1_us_station_matches.parquet")
stations = stations.query(f"match_dist_m<{200}")
stations = stations[stations['usgs_site_no'].astype(str).str.len() == 8]
print(f"{len(stations):,} stations in DFMS.v1 with match_dist<200m")
stations.tail(10)

1,848 stations in DFMS.v1 with match_dist<200m

,usgs_site_no,node_id,reach_id,swot_obs,swot_orbit,match_dist_m,sword_width_m,sword_facc_km2,sword_lakeflag,sword_strm_order,sword_river_name,drain_area_km2,da_ratio,filter_path
2260,15564900,81220100420221,81220100421,5,164 265 293 442 470,86.996453,226.0,47405.496090,0,3,Koyukuk River,46593.92010,0.017418,distance_and_da
2263,15580095,81310200050881,81310200051,4,71 276 377 582,84.081914,84.0,1721.631536,0,1,Niukluk River,1831.12293,0.059795,distance_and_da
2265,15746900,81350100390341,81350100391,5,220 405 433 498 526,52.257224,48.0,518.158370,0,1,Wulik River,494.68809,0.047445,distance_and_da
2266,15747000,81350100360061,81350100361,4,220 248 405 433,55.053936,63.0,1889.524105,0,1,Wulik River,1825.94295,0.034821,distance_and_da
2267,15820000,81360000110921,81360000111,5,80 108 349 377 386,79.199592,63.0,3626.818962,0,1,NODATA,4402.98300,0.176281,distance_and_da
2268,15896000,81390200030541,81390200031,4,15 24 293 302 321,29.124972,42.0,8516.591890,0,2,NODATA,8650.56660,0.015487,distance_and_da
2269,15908000,81390400150641,81390400151,5,24 52 265 293 330,74.709554,126.0,5129.052091,0,2,Sagavanirktok River,4791.48150,0.070452,distance_and_da
2270,15910000,81390400150111,81390400151,5,24 52 265 293 330,70.294006,105.0,5348.125158,0,2,Sagavanirktok River,5697.97800,0.061399,distance_and_da
2271,15955000,81390800010251,81390800011,5,265 274 302 543 571,133.298937,113.5,4893.908002,0,2,Canning River,4998.68070,0.020960,distance_and_da
2272,15980000,81390900160651,81390900161,6,237 246 274 515 543 552 580,20.411896,36.0,1703.006427,0,1,Hulahula Riverr,1779.32313,0.042891,distance_and_da

In [30]:
usgs_codes = "USGS-"+np.array(stations.usgs_site_no)

In [33]:
list(usgs_codes)

['USGS-01010000',
 'USGS-01010500',
 'USGS-01014000',
 'USGS-01021500',
 'USGS-01029500',
 'USGS-01030000',
 'USGS-01030500',
 'USGS-01031500',
 'USGS-01033000',
 'USGS-01034500',
 'USGS-01036390',
 'USGS-01042500',
 'USGS-01046500',
 'USGS-01047000',
 'USGS-01047150',
 'USGS-01048000',
 'USGS-01049205',
 'USGS-01049265',
 'USGS-01054500',
 'USGS-01088400',
 'USGS-01092000',
 'USGS-01096550',
 'USGS-01098840',
 'USGS-01098860',
 'USGS-01131500',
 'USGS-01144500',
 'USGS-01154500',
 'USGS-01161280',
 'USGS-01170000',
 'USGS-01170006',
 'USGS-01170500',
 'USGS-01172000',
 'USGS-01172003',
 'USGS-01183999',
 'USGS-01190070',
 'USGS-01193000',
 'USGS-01200500',
 'USGS-01200600',
 'USGS-01312000',
 'USGS-01315000',
 'USGS-01315081',
 'USGS-01327750',
 'USGS-01328752',
 'USGS-01328770',
 'USGS-01329500',
 'USGS-01329550',
 'USGS-01329561',
 'USGS-01329650',
 'USGS-01331095',
 'USGS-01335505',
 'USGS-01335754',
 'USGS-01335755',
 'USGS-01335770',
 'USGS-01342602',
 'USGS-01342702',
 'USGS-01346000',
 'USGS-01349527',
 'USGS-01349530',
 'USGS-01354083',
 'USGS-01354250',
 'USGS-01354500',
 'USGS-01355500',
 'USGS-01357500',
 'USGS-01358000',
 'USGS-01359139',
 'USGS-01372058',
 'USGS-01427000',
 'USGS-01427207',
 'USGS-01427510',
 'USGS-01434000',
 'USGS-01438500',
 'USGS-01439722',
 'USGS-01440200',
 'USGS-01446500',
 'USGS-01451000',
 'USGS-01451192',
 'USGS-01453000',
 'USGS-01454653',
 'USGS-01454700',
 'USGS-01457500',
 'USGS-01461500',
 'USGS-01462000',
 'USGS-01462500',
 'USGS-01467024',
 'USGS-01472105',
 'USGS-01472162',
 'USGS-01473193',
 'USGS-01473730',
 'USGS-01474500',
 'USGS-01502707',
 'USGS-01503000',
 'USGS-01503500',
 'USGS-01512500',
 'USGS-01531500',
 'USGS-01533400',
 'USGS-01536500',
 'USGS-01537850',
 'USGS-01541180',
 'USGS-01541500',
 'USGS-01542500',
 'USGS-01545500',
 'USGS-01545800',
 'USGS-01551500',
 'USGS-01553025',
 'USGS-01559000',
 'USGS-01562000',
 'USGS-01565810',
 'USGS-01567000',
 'USGS-01570500',
 'USGS-01578310',
 'USGS-01618000',
 'USGS-01628800',
 'USGS-01629275',
 'USGS-01636290',
 'USGS-01636500',
 'USGS-01636740',
 'USGS-01636750',
 'USGS-01636760',
 'USGS-01636780',
 'USGS-01636790',
 'USGS-01638060',
 'USGS-01638065',
 'USGS-01638500',
 'USGS-01638530',
 'USGS-01638540',
 'USGS-01638615',
 'USGS-01638620',
 'USGS-01643117',
 'USGS-01643130',
 'USGS-01643583',
 'USGS-01643586',
 'USGS-01643605',
 'USGS-01643611',
 'USGS-01643613',
 'USGS-01643618',
 'USGS-01644150',
 'USGS-01644281',
 'USGS-01645310',
 'USGS-01646400',
 'USGS-01668000',
 'USGS-01668020',
 'USGS-02024600',
 'USGS-02024750',
 'USGS-02024752',
 'USGS-02025500',
 'USGS-02025510',
 'USGS-02026000',
 'USGS-02029000',
 'USGS-02035600',
 'USGS-02041500',
 'USGS-02074218',
 'USGS-02074980',
 'USGS-02075045',
 'USGS-02079000',
 'USGS-02079500',
 'USGS-02080500',
 'USGS-02081000',
 'USGS-02081022',
 'USGS-02081054',
 'USGS-02081133',
 'USGS-02084000',
 'USGS-02084173',
 'USGS-02084472',
 'USGS-02087500',
 'USGS-02089500',
 'USGS-02096879',
 'USGS-02096960',
 'USGS-02098198',
 'USGS-02098206',
 'USGS-02098210',
 'USGS-02102000',
 'USGS-02102176',
 'USGS-02104000',
 'USGS-02105500',
 'USGS-02105769',
 'USGS-02107544',
 'USGS-02110815',
 'USGS-02126000',
 'USGS-02127500',
 'USGS-02129000',
 'USGS-02130000',
 'USGS-02130561',
 'USGS-02131000',
 'USGS-02131010',
 'USGS-02135200',
 'USGS-02135210',
 'USGS-02136358',
 'USGS-02145910',
 'USGS-02146000',
 'USGS-02147000',
 'USGS-02147020',
 'USGS-02147801',
 'USGS-02148000',
 'USGS-02148312',
 'USGS-02156409',
 'USGS-02156500',
 'USGS-02166501',
 'USGS-02168504',
 'USGS-02169000',
 'USGS-02169500',
 'USGS-02169624',
 'USGS-02169625',
 'USGS-02169750',
 'USGS-02171001',
 'USGS-02171560',
 'USGS-02171650',
 'USGS-02172040',
 'USGS-02175000',
 'USGS-02175025',
 'USGS-02178500',
 'USGS-02182200',
 'USGS-02183610',
 'USGS-02184000',
 'USGS-02187252',
 'USGS-02188000',
 'USGS-02188750',
 'USGS-02192000',
 'USGS-02195520',
 'USGS-02196484',
 'USGS-02196485',
 'USGS-02196670',
 'USGS-02196993',
 'USGS-02197000',
 'USGS-02197065',
 'USGS-02197320',
 'USGS-02197375',
 'USGS-02197500',
 'USGS-02198500',
 'USGS-02198720',
 'USGS-02198759',
 'USGS-02198840',
 'USGS-02203536',
 'USGS-02212510',
 'USGS-02213000',
 'USGS-02213700',
 'USGS-02214265',
 'USGS-02214325',
 'USGS-02215000',
 'USGS-02215260',
 'USGS-02215320',
 'USGS-02215500',
 'USGS-02218000',
 'USGS-02218500',
 'USGS-02219500',
 'USGS-02220500',
 'USGS-02222510',
 'USGS-02223000',
 'USGS-02223040',
 'USGS-02223056',
 'USGS-02223248',
 'USGS-02223250',
 'USGS-02223382',
 'USGS-02223500',
 'USGS-02224310',
 'USGS-02224500',
 'USGS-02224910',
 'USGS-02224940',
 'USGS-02225000',
 'USGS-02225810',
 'USGS-02226000',
 'USGS-02226160',
 'USGS-02228000',
 'USGS-02228070',
 'USGS-02231220',
 'USGS-02231253',
 'USGS-02231254',
 'USGS-02232000',
 'USGS-02232400',
 'USGS-02234010',
 'USGS-02234440',
 'USGS-02236000',
 'USGS-02236125',
 'USGS-02244440',
 'USGS-02246621',
 'USGS-02292490',
 'USGS-02292900',
 'USGS-02312720',
 'USGS-02312722',
 'USGS-02312762',
 'USGS-02319502',
 'USGS-02319900',
 'USGS-02320060',
 'USGS-02320400',
 'USGS-02320502',
 'USGS-02323000',
 'USGS-02323500',
 'USGS-02330150',
 'USGS-02333000',
 'USGS-02334000',
 'USGS-02334300',
 'USGS-02336449',
 'USGS-02336490',
 'USGS-02336500',
 'USGS-02336650',
 'USGS-02337070',
 'USGS-02337260',
 'USGS-02337445',
 'USGS-02337457',
 'USGS-02338000',
 'USGS-02338305',
 'USGS-02338315',
 'USGS-02338500',
 'USGS-02338712',
 'USGS-02338713',
 'USGS-02339000',
 'USGS-02339350',
 'USGS-02339402',
 'USGS-02339500',
 'USGS-02341460',
 'USGS-02341500',
 'USGS-02341505',
 'USGS-02341508',
 'USGS-02342110',
 'USGS-02342880',
 'USGS-02342881',
 'USGS-02342940',
 'USGS-02343241',
 'USGS-02343260',
 'USGS-02343500',
 'USGS-02343801',
 'USGS-02343805',
 'USGS-02344000',
 'USGS-02344040',
 'USGS-02347500',
 'USGS-02348060',
 'USGS-02348350',
 'USGS-02349500',
 'USGS-02349501',
 'USGS-02349605',
 'USGS-02349800',
 'USGS-02350000',
 'USGS-02350001',
 'USGS-02350405',
 'USGS-02350511',
 'USGS-02352650',
 'USGS-02352700',
 'USGS-02352790',
 'USGS-02352795',
 'USGS-02352805',
 'USGS-02352939',
 'USGS-02352945',
 'USGS-02353000',
 'USGS-02353075',
 'USGS-02353080',
 'USGS-02355660',
 'USGS-02355662',
 'USGS-02355670',
 'USGS-02355685',
 'USGS-02358000',
 'USGS-02358634',
 'USGS-02358664',
 'USGS-02358684',
 'USGS-02359051',
 'USGS-02359098',
 'USGS-02359101',
 'USGS-02359103',
 'USGS-02359170',
 'USGS-02359223',
 'USGS-02361500',
 'USGS-02364200',
 'USGS-02365000',
 'USGS-02366500',
 'USGS-02371698',
 'USGS-02372430',
 'USGS-02372475',
 'USGS-02374250',
 'USGS-02375500',
 'USGS-02376033',
 'USGS-02376047',
 'USGS-02376050',
 'USGS-02376056',
 'USGS-02376070',
 'USGS-02380002',
 'USGS-02380003',
 'USGS-02380004',
 'USGS-02380005',
 'USGS-02380006',
 'USGS-02380007',
 'USGS-02380008',
 'USGS-02380009',
 'USGS-02380012',
 'USGS-02380015',
 'USGS-02387500',
 'USGS-02387530',
 'USGS-02387650',
 'USGS-02387670',
 'USGS-02387770',
 'USGS-02388530',
 'USGS-02393480',
 'USGS-02394550',
 'USGS-02394775',
 'USGS-02395000',
 'USGS-02395980',
 'USGS-02397000',
 'USGS-02397100',
 'USGS-02397530',
 'USGS-02398500',
 'USGS-02399500',
 'USGS-02400175',
 'USGS-02400350',
 'USGS-02400496',
 'USGS-02400500',
 'USGS-02401330',
 'USGS-02402500',
 'USGS-02404400',
 'USGS-02405200',
 'USGS-02407000',
 'USGS-02411000',
 'USGS-02411590',
 'USGS-02412500',
 'USGS-02413350',
 'USGS-02413500',
 'USGS-02413970',
 'USGS-02414000',
 'USGS-02414300',
 'USGS-02414500',
 'USGS-02414715',
 'USGS-02417505',
 'USGS-02418500',
 'USGS-02419500',
 'USGS-02419890',
 'USGS-02419893',
 'USGS-02420000',
 'USGS-02421350',
 'USGS-02421351',
 'USGS-02424590',
 'USGS-02425000',
 'USGS-02427505',
 'USGS-02428400',
 'USGS-02428401',
 'USGS-02429540',
 'USGS-02429982',
 'USGS-02431011',
 'USGS-02433150',
 'USGS-02433496',
 'USGS-02437100',
 'USGS-02449500',
 'USGS-02450400',
 'USGS-02450500',
 'USGS-02451920',
 'USGS-02453050',
 'USGS-02453700',
 'USGS-02455400',
 'USGS-02455500',
 'USGS-02456500',
 'USGS-02458000',
 'USGS-02465000',
 'USGS-02465280',
 'USGS-02466000',
 'USGS-02466030',
 'USGS-02466031',
 'USGS-02467000',
 'USGS-02467001',
 'USGS-02467050',
 'USGS-02469525',
 'USGS-02469761',
 'USGS-02469762',
 'USGS-02469765',
 'USGS-02470500',
 'USGS-02470629',
 'USGS-02470700',
 'USGS-02471019',
 'USGS-02473000',
 'USGS-02473320',
 'USGS-02473360',
 'USGS-02478500',
 'USGS-02479000',
 'USGS-02479310',
 'USGS-02479330',
 'USGS-02484595',
 'USGS-02485000',
 'USGS-02488000',
 'USGS-02488460',
 'USGS-02488500',
 'USGS-02488710',
 'USGS-02489000',
 'USGS-02489500',
 'USGS-02492000',
 'USGS-02492110',
 'USGS-02492112',
 'USGS-02492600',
 'USGS-02492700',
 'USGS-03011020',
 'USGS-03011500',
 'USGS-03015310',
 'USGS-03022000',
 'USGS-03023500',
 'USGS-03025500',
 'USGS-03029500',
 'USGS-03030500',
 'USGS-03030515',
 'USGS-03031500',
 'USGS-03031550',
 'USGS-03033000',
 'USGS-03039035',
 'USGS-03042000',
 'USGS-03043810',
 'USGS-03044000',
 'USGS-03072500',
 'USGS-03072655',
 'USGS-03073751',
 'USGS-03075000',
 'USGS-03075070',
 'USGS-03083500',
 'USGS-03085000',
 'USGS-03086000',
 'USGS-03099600',
 'USGS-03104500',
 'USGS-03107500',
 'USGS-03124800',
 'USGS-03144500',
 'USGS-03146500',
 'USGS-03150300',
 'USGS-03150500',
 'USGS-03168000',
 'USGS-03169000',
 'USGS-03171000',
 'USGS-03171500',
 'USGS-03174005',
 'USGS-03176500',
 'USGS-03182500',
 'USGS-03183500',
 'USGS-03184500',
 'USGS-03185400',
 'USGS-03193000',
 'USGS-03197950',
 'USGS-03197990',
 'USGS-03198000',
 'USGS-03214980',
 'USGS-03216000',
 'USGS-03221000',
 'USGS-03227107',
 'USGS-03231500',
 'USGS-03261500',
 'USGS-03270500',
 'USGS-03271207',
 'USGS-03271500',
 'USGS-03271601',
 'USGS-03272100',
 'USGS-03274000',
 'USGS-03277200',
 'USGS-03282000',
 'USGS-03284500',
 'USGS-03286500',
 'USGS-03287000',
 'USGS-03290080',
 'USGS-03294500',
 'USGS-03302058',
 'USGS-03302060',
 'USGS-03303500',
 'USGS-03304300',
 'USGS-03315000',
 'USGS-03319885',
 'USGS-03320000',
 'USGS-03321500',
 'USGS-03322900',
 'USGS-03322985',
 'USGS-03323000',
 'USGS-03323500',
 'USGS-03324300',
 'USGS-03324500',
 'USGS-03327000',
 'USGS-03327500',
 'USGS-03329000',
 'USGS-03329900',
 'USGS-03331753',
 'USGS-03332345',
 'USGS-03332555',
 'USGS-03333000',
 'USGS-03333050',
 'USGS-03333080',
 'USGS-03333270',
 'USGS-03335500',
 'USGS-03335680',
 'USGS-03336000',
 'USGS-03339131',
 'USGS-03340500',
 'USGS-03341500',
 'USGS-03342000',
 'USGS-03343000',
 'USGS-03343010',
 'USGS-03348000',
 'USGS-03352953',
 'USGS-03353611',
 'USGS-03371500',
 'USGS-03373500',
 'USGS-03373980',
 'USGS-03374000',
 'USGS-03374100',
 'USGS-03374105',
 'USGS-03377500',
 'USGS-03378500',
 'USGS-03411000',
 'USGS-03411500',
 'USGS-03414000',
 'USGS-03417500',
 'USGS-03418200',
 'USGS-03418420',
 'USGS-03420130',
 'USGS-03421000',
 'USGS-03421900',
 'USGS-03424860',
 'USGS-03425000',
 'USGS-03426310',
 'USGS-03426500',
 'USGS-03427500',
 'USGS-03427733',
 'USGS-03431400',
 'USGS-03431500',
 'USGS-03431790',
 'USGS-03434800',
 'USGS-03434890',
 'USGS-03435000',
 'USGS-03435006',
 'USGS-03436500',
 'USGS-03451500',
 'USGS-03453500',
 'USGS-03454500',
 'USGS-03454757',
 'USGS-03455000',
 'USGS-03467900',
 'USGS-03470500',
 'USGS-03477015',
 'USGS-03478622',
 'USGS-03478625',
 'USGS-03486700',
 'USGS-03490210',
 'USGS-03490250',
 'USGS-03490900',
 'USGS-03491600',
 'USGS-03495500',
 'USGS-03499100',
 'USGS-03499114',
 'USGS-03499115',
 'USGS-03503000',
 'USGS-03513000',
 'USGS-03515000',
 'USGS-03519510',
 'USGS-03519699',
 'USGS-03519750',
 'USGS-03533000',
 'USGS-03534600',
 'USGS-03534610',
 'USGS-03534618',
 'USGS-03538117',
 'USGS-03555000',
 'USGS-03556600',
 'USGS-03556610',
 'USGS-03570510',
 'USGS-03571850',
 'USGS-03574680',
 'USGS-03575450',
 'USGS-03575736',
 'USGS-03577119',
 'USGS-03577120',
 'USGS-03582630',
 'USGS-03585000',
 'USGS-03593500',
 'USGS-03598265',
 'USGS-03599310',
 'USGS-03599350',
 'USGS-03599352',
 'USGS-03599360',
 'USGS-03599362',
 'USGS-03599365',
 'USGS-03599410',
 'USGS-03599411',
 'USGS-03599413',
 'USGS-03599423',
 'USGS-03599425',
 'USGS-03600352',
 'USGS-03600354',
 'USGS-03600382',
 'USGS-03600415',
 'USGS-03600425',
 'USGS-03601555',
 'USGS-03601557',
 'USGS-03601558',
 'USGS-03601600',
 'USGS-03601635',
 'USGS-03601645',
 'USGS-03601990',
 'USGS-03603997',
 'USGS-03604000',
 'USGS-03604270',
 'USGS-03604280',
 'USGS-03604400',
 'USGS-04024000',
 'USGS-04032100',
 'USGS-04039900',
 'USGS-04040000',
 'USGS-04040018',
 'USGS-04040020',
 'USGS-04045500',
 'USGS-04056500',
 'USGS-04057004',
 'USGS-04058950',
 'USGS-04058990',
 'USGS-04059000',
 'USGS-04059032',
 'USGS-04062017',
 'USGS-04062500',
 'USGS-04063500',
 'USGS-04063522',
 'USGS-04065722',
 'USGS-04066000',
 'USGS-04066003',
 'USGS-04066030',
 'USGS-04066800',
 'USGS-04067000',
 'USGS-04067648',
 'USGS-04069416',
 'USGS-04069500',
 'USGS-04071000',
 'USGS-04071500',
 'USGS-04075156',
 'USGS-04077100',
 'USGS-04077410',
 'USGS-04081120',
 'USGS-04081500',
 'USGS-04082400',
 'USGS-04082450',
 'USGS-04084500',
 'USGS-04085000',
 'USGS-04085058',
 'USGS-04085138',
 'USGS-04087000',
 'USGS-04087170',
 'USGS-04096800',
 'USGS-04097000',
 'USGS-04101000',
 'USGS-04101225',
 'USGS-04101500',
 'USGS-04108660',
 'USGS-04108690',
 'USGS-04111033',
 'USGS-04111055',
 'USGS-04113050',
 'USGS-04113155',
 'USGS-04114520',
 'USGS-04116000',
 'USGS-04118680',
 'USGS-04119065',
 'USGS-04125550',
 'USGS-04135616',
 'USGS-04135625',
 'USGS-04135634',
 'USGS-04136110',
 'USGS-04136550',
 'USGS-04136750',
 'USGS-04137550',
 'USGS-04137720',
 'USGS-04152065',
 'USGS-04152080',
 'USGS-04154500',
 'USGS-04156000',
 'USGS-04156100',
 'USGS-04156200',
 'USGS-04156500',
 'USGS-04156505',
 'USGS-04156510',
 'USGS-04157000',
 'USGS-04157059',
 'USGS-04157060',
 'USGS-04157061',
 'USGS-04159130',
 'USGS-04176537',
 'USGS-04180600',
 'USGS-04180610',
 'USGS-04182769',
 'USGS-04182900',
 'USGS-04183105',
 'USGS-04183500',
 'USGS-04185935',
 'USGS-04191500',
 'USGS-04192500',
 'USGS-04193500',
 'USGS-04197137',
 'USGS-04198008',
 'USGS-04213453',
 'USGS-04213470',
 'USGS-04214020',
 'USGS-04218602',
 'USGS-04218710',
 'USGS-04219501',
 'USGS-04231500',
 'USGS-04231800',
 'USGS-04235600',
 'USGS-04237020',
 'USGS-04237496',
 'USGS-04237500',
 'USGS-04237575',
 'USGS-04246500',
 'USGS-04247055',
 'USGS-04247060',
 'USGS-04247080',
 'USGS-04247500',
 'USGS-04248250',
 'USGS-04262000',
 'USGS-04263000',
 'USGS-04263475',
 'USGS-04264331',
 'USGS-04265432',
 'USGS-04265437',
 'USGS-04265440',
 'USGS-04265446',
 'USGS-04267500',
 'USGS-04267750',
 'USGS-04268000',
 'USGS-04268230',
 'USGS-04268700',
 'USGS-04280754',
 'USGS-04282576',
 'USGS-04294000',
 'USGS-05020500',
 'USGS-05062130',
 'USGS-05079000',
 'USGS-05082000',
 'USGS-05082500',
 'USGS-05083500',
 'USGS-05092000',
 'USGS-05137500',
 'USGS-05242300',
 'USGS-05244495',
 'USGS-05244500',
 'USGS-05247500',
 'USGS-05261000',
 'USGS-05267000',
 'USGS-05270000',
 'USGS-05270530',
 'USGS-05270600',
 'USGS-05270700',
 'USGS-05273510',
 'USGS-05273620',
 'USGS-05273655',
 'USGS-05273660',
 'USGS-05273670',
 'USGS-05273680',
 'USGS-05273690',
 'USGS-05273750',
 'USGS-05275500',
 'USGS-05275550',
 'USGS-05275600',
 'USGS-05275650',
 'USGS-05283300',
 'USGS-05283500',
 'USGS-05288100',
 'USGS-05288910',
 'USGS-05288930',
 'USGS-05288950',
 'USGS-05314550',
 'USGS-05314560',
 'USGS-05316580',
 'USGS-05316685',
 'USGS-05316760',
 'USGS-05316770',
 'USGS-05317250',
 'USGS-05320000',
 'USGS-05321995',
 'USGS-05322000',
 'USGS-05325000',
 'USGS-05325300',
 'USGS-05326450',
 'USGS-05330000',
 'USGS-05330050',
 'USGS-05330680',
 'USGS-05330710',
 'USGS-05330713',
 'USGS-05330755',
 'USGS-05330815',
 'USGS-05330860',
 'USGS-05330880',
 'USGS-05330905',
 'USGS-05330906',
 'USGS-05330910',
 'USGS-05330917',
 'USGS-05330920',
 'USGS-05331000',
 'USGS-05331400',
 'USGS-05331555',
 'USGS-05331578',
 'USGS-05331580',
 'USGS-05335551',
 'USGS-05337082',
 'USGS-05338650',
 'USGS-05339015',
 'USGS-05340200',
 'USGS-05340420',
 'USGS-05340500',
 'USGS-05340540',
 'USGS-05340552',
 'USGS-05340600',
 'USGS-05341510',
 'USGS-05341820',
 'USGS-05344490',
 'USGS-05355235',
 'USGS-05358500',
 'USGS-05362500',
 'USGS-05365500',
 'USGS-05365550',
 'USGS-05366800',
 'USGS-05367000',
 'USGS-05368500',
 'USGS-05369000',
 'USGS-05371200',
 'USGS-05385000',
 'USGS-05388340',
 'USGS-05392000',
 'USGS-05393700',
 'USGS-05395000',
 'USGS-05400000',
 'USGS-05400760',
 'USGS-05400980',
 'USGS-05404000',
 'USGS-05407000',
 'USGS-05418720',
 'USGS-05421330',
 'USGS-05421400',
 'USGS-05421440',
 'USGS-05421740',
 'USGS-05421770',
 'USGS-05421840',
 'USGS-05422110',
 'USGS-05425500',
 'USGS-05427085',
 'USGS-05427530',
 'USGS-05427570',
 'USGS-05430500',
 'USGS-05437500',
 'USGS-05437610',
 'USGS-05437645',
 'USGS-05440700',
 'USGS-05442200',
 'USGS-05442300',
 'USGS-05443500',
 'USGS-05446500',
 'USGS-05451050',
 'USGS-05451500',
 'USGS-05451750',
 'USGS-05451770',
 'USGS-05451785',
 'USGS-05451810',
 'USGS-05451910',
 'USGS-05452500',
 'USGS-05453100',
 'USGS-05453520',
 'USGS-05454130',
 'USGS-05454450',
 'USGS-05454500',
 'USGS-05455700',
 'USGS-05457470',
 'USGS-05457505',
 'USGS-05457700',
 'USGS-05458150',
 'USGS-05458300',
 'USGS-05458500',
 'USGS-05461000',
 'USGS-05461500',
 'USGS-05464000',
 'USGS-05464020',
 'USGS-05464090',
 'USGS-05464302',
 'USGS-05464315',
 'USGS-05464317',
 'USGS-05464325',
 'USGS-05464420',
 'USGS-05464450',
 'USGS-05464470',
 'USGS-05464480',
 'USGS-05464500',
 'USGS-05464730',
 'USGS-05464765',
 'USGS-05464780',
 'USGS-05464810',
 'USGS-05465000',
 'USGS-05465095',
 'USGS-05465500',
 'USGS-05465700',
 'USGS-05472540',
 'USGS-05472700',
 'USGS-05473000',
 'USGS-05473065',
 'USGS-05473330',
 'USGS-05473420',
 'USGS-05473430',
 'USGS-05479500',
 'USGS-05480500',
 'USGS-05481300',
 'USGS-05481500',
 'USGS-05481650',
 'USGS-05482000',
 'USGS-05482400',
 'USGS-05482500',
 'USGS-05485500',
 'USGS-05487500',
 'USGS-05489200',
 'USGS-05489620',
 'USGS-05489800',
 'USGS-05490130',
 'USGS-05490170',
 ...]

In [39]:
locations = waterdata.get_monitoring_locations(monitoring_location_id=list(usgs_codes[0:100]), properties=['monitoring_location_name'])

In [51]:
timeseries = "2023-04-01T00:00:00Z/2026-03-30T12:31:12Z"
test = waterdata.get_latest_continuous(monitoring_location_id=list(usgs_codes[0:200]), parameter_code="00065", statistic_id="00011",
                                       time=timeseries)[0]

In [52]:
test

,geometry,time_series_id,monitoring_location_id,parameter_code,statistic_id,time,value,unit_of_measure,approval_status,qualifier,last_modified,latest_continuous_id
0,POINT (-73.66108 42.82483),9cee4a09f33b45ea863556c4dd06bb38,USGS-01335755,00065,00011,2026-02-28 19:00:00+00:00,NaN,ft,Provisional,[SEASONAL],2026-03-03 00:23:19.703807+00:00,a16174c6-2739-4cda-9c4d-e3d177c5e43c
1,POINT (-68.58528 47.28333),c289a526bea1493bb33ee6e8dd389b92,USGS-01014000,00065,00011,2026-03-03 02:30:00+00:00,4.95,ft,Provisional,None,2026-03-03 02:37:17.794271+00:00,cf4cbfea-0db7-4762-898b-c58e33c506f0
2,POINT (-69.31472 45.175),4a9c71c9a2c545c2a300e905d6e42f4e,USGS-01031500,00065,00011,2026-03-03 02:30:00+00:00,2.05,ft,Provisional,None,2026-03-03 02:47:14.192263+00:00,9d76ed77-dbea-45ab-bc27-4a71ec407ef7
3,POINT (-68.65139 45.23611),f9e0c9ff72a848b4af2aeac960ad59af,USGS-01034500,00065,00011,2026-03-03 02:30:00+00:00,3.31,ft,Provisional,None,2026-03-03 02:41:12.726023+00:00,58314b2e-3caa-4d47-80f2-80bcc4cd016d
4,POINT (-68.69667 44.82667),0addb5726065431caefd031624cacbd1,USGS-01036390,00065,00011,2026-03-03 02:30:00+00:00,NaN,ft,Provisional,[EQUIP],2026-03-03 02:40:15.121879+00:00,c7f22653-62a8-40fb-baef-cd6ee4c12e63
...,...,...,...,...,...,...,...,...,...,...,...,...
107,POINT (-80.69843 34.33208),16096cbe18494a2cb6eef44014940123,USGS-02147801,00065,00011,2026-03-03 03:15:00+00:00,10.92,ft,Provisional,None,2026-03-03 03:21:32.269802+00:00,c1aa007f-8dca-4f50-b796-ef4dce15b916
108,POINT (-81.42121 34.59514),3a173d4667394e3ea226ca3ac55611eb,USGS-02156500,00065,00011,2026-03-03 03:15:00+00:00,3.30,ft,Provisional,None,2026-03-03 03:28:17.514640+00:00,7d387806-2b74-492b-89a3-7aeeea36b020
109,POINT (-81.20954 34.05098),27db11808a564559806904384f75a869,USGS-02168504,00065,00011,2026-03-03 03:15:00+00:00,3.90,ft,Provisional,None,2026-03-03 03:29:17.519245+00:00,ec34a9d4-ddd6-4e09-9c80-5f968c525fc3
110,POINT (-73.93075 42.83053),bdc06b974c514f798263ec434017ca7a,USGS-01354500,00065,00011,2026-03-03 03:25:00+00:00,10.02,ft,Provisional,None,2026-03-03 03:31:16.100168+00:00,3364ed5c-59d7-4a14-8416-b5aff746c5c4
111,POINT (-74.79528 41.30917),25359dd3f6984670bf19f7bc00887bf9,USGS-01438500,00065,00011,2026-03-03 03:30:00+00:00,6.44,ft,Provisional,None,2026-03-03 03:35:21.180716+00:00,ede2af0e-4105-4335-be73-29294a421157

In [15]:
pcodes,metadata = waterdata.get_reference_table("parameter-codes")
# display(pcodes.head())

streamflow_pcodes = pcodes[pcodes['parameter_name'].str.contains('site|type', case=False, na=False)]
display(streamflow_pcodes[['parameter_code', 'parameter_name', 'parameter_description']])

,parameter_code,parameter_name,parameter_description
766,04119,Verticals in composite,"Verticals in composite sample, number"
3866,50276,Filter type,"Filter type, code"
3869,50280,Site visit purpose,"Site visit purpose, code"
13741,70001,Composite loctn in X-section,Composite location in cross section
14153,72326,Opposite direction,Opposite direction content quality assurance p...
15134,82923,"Atm. Dep. Type, wet","Atmospheric deposition type, wet, code"
15186,83205,"Atmos deposition type, bulk","Atmospheric deposition type, bulk, code"
15251,84164,Sampler type,"Sampler type, code"
15252,84171,Sample splitter type,"Sample splitter type, field, code"
15255,84174,POCIS sorbent type,"POCIS sorbent type, code"
15266,84185,"Sorbent type, SPMD, code","Semipermeable membrane device sorbent type, code"
15267,84186,"Sorbent type, SPATT, code",Solid phase adsorption toxin tracking (SPATT) ...
15706,90003,Type of well,"Type of well, code"
18713,99100,Type of blank solution,"Type of blank solution, code"
18715,99102,Type of blank sample,"Type of blank sample, code"
18718,99105,Type of replicate,"Type of replicate, code"
18719,99106,Type of spike,"Type of spike, code"
18724,99111,Type of QA data,Type of quality assurance data associated with...